# Generated by Django 5.2.1 on 2025-08-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='email',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='temp@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Cat'), ('SW', 'Dog '), ('OW', 'Other')], max_length=2),
        ),
    ]
